// svelte/src/App.svelte
<script lang="ts">
  const todos = [
    { id: 1, text: "Hello", done: true },
    { id: 2, text: "Hallo", done: false },
    { id: 3, text: "Bonjour", done: false },
  ];

  $: uncompletedTodos = todos.filter((todo) => !todo.done);

  let text = "";
  function resetText() {
    text = "";
  }

  function addTodo() {
    todos.push({ id: todos.length + 1, text, done: false });
    resetText();
  }
</script>

<main>
  <h1>Todo</h1>
  <ul>
    {#each uncompletedTodos as todo}
      <li>
        <input type="checkbox" bind:checked={todo.done} />
        {todo.text}
      </li>
    {/each}
  </ul>
  <input type="text" bind:value={text} />
  <button on:click={addTodo}>Add todo</button>
</main>

<style>
  main {
    max-width: 600px;
    margin: 0 auto;
    padding: 1rem;
  }
</style>

// vue/src/App.vue
<script setup lang="ts">
import { ref, computed } from "vue";

const todos = ref([
  { id: 1, text: "Hello", done: true },
  { id: 2, text: "Hallo", done: false },
  { id: 3, text: "Bonjour", done: false },
]);

const uncompletedTodos = computed(() => {
  return todos.value.filter((todo) => !todo.done);
});

const text = ref("");
function resetText() {
  text.value = "";
}

function addTodo() {
  todos.value.push({
    id: todos.value.length + 1,
    text: text.value,
    done: false,
  });
  resetText();
}
</script>

<template>
  <main>
    <h1>Todo List</h1>
    <ul>
      <li v-for="todo in uncompletedTodos" :key="todo.id">
        <input type="checkbox" v-model="todo.done" />
        {{ todo.text }}
      </li>
    </ul>
    <input type="text" v-model="text" />
    <button @click="addTodo">Add Todo</button>
  </main>
</template>

<style>
main {
  max-width: 600px;
  margin: 0 auto;
  padding: 1rem;
}
</style>
